version: "3"

volumes:
  db_data:

services:
  cybersec-db:
    image: postgres:alpine
    container_name: cybersec-db
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: codevault
      POSTGRES_DB: codevault
    expose:
      - "5430"
    ports:
      - "5430:5430"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - overlay
    command: -p 5430

networks:
  overlay:
